name: Notify on Push

on:
  push:
    branches:
      - main  # Change this to match the branch you want notifications for

jobs:
  email_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.up.pt
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "semisup: new push"
          body: "A new push has been made to the repository."
          to: "rpcruz@fe.up.pt"
          from: "rpcruz@fe.up.pt"
